server:
  port: 8080

spring:
  data:
    mongodb:
      uri: ${MONGO_URI}
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

cloudinary:
  cloud-name: ${CLOUD_NAME}
  api-key: ${CLOUD_API_KEY}
  api-secret: ${CLOUD_API_SECRET}

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000
