server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb+srv://losser:2GGDSn_iP6zU*_M@cluster0.jazo4qb.mongodb.net/travelapp?retryWrites=true&w=majority&appName=Cluster0
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

cloudinary:
  cloud-name: ddbaf9fxq
  api-key: 565386529872952
  api-secret: LUxq-2tWrYLHPmmOxqh6zyeuw88

jwt:
  secret: hjR8m29X@dP8ZsWkLqYxEfMtVcBnZgKrXjTnWpLsQvLuZcVuGtIjYhTgRfEdQsBa
  expiration: 86400000
